apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs
provisioner: nfs-subdir-external-provisioner
parameters:
  archiveOnDelete: "false"
  nfsServer: 10.112.12.190
  pathPattern: "/exports"
