version: '3.5'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password --sql_mode="" --character-set-server=utf8 --collation-server=utf8_slovenian_ci --init-connect='SET NAMES UTF8;'
    restart: always
    env_file: .env
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - '3306:3306'
    expose:
      - '3306'
    networks:
      - internal
      - external
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE

networks:
  external:
    driver: bridge
  internal:
    driver: bridge

volumes:
  db-data: