apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  rootUser: cm9vdA==  # Base64 encoded 'root'
  rootHost: JQ==      # Base64 encoded '%'
  rootPassword: YWRtaW4=  # Base64 encoded 'admin'
