version: '3'
services:
  nfs-server:
    image: itsthenetwork/nfs-server-alpine:latest
    container_name: nfs-server
    privileged: true
    environment:
      - SHARED_DIRECTORY=/nfsshare
      - SYNC=true
    volumes:
      - reto3-tec:/nfsshare
    ports:
      - "2049:2049/tcp"
      - "2049:2049/udp"
      - "32765:32765/tcp"
      - "32765:32765/udp"
      - "32766:32766/tcp"
      - "32766:32766/udp"
      - "32767:32767/tcp"
      - "32767:32767/udp"
    networks:
      - nfs_network
    command: sh -c "rpcbind -w && /entrypoint.sh"

networks:
  nfs_network:
volumes:
  reto3-tec: