apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-rwx
  annotations:
    openebs.io/cas-type: nfsrwx
    cas.openebs.io/config: |
      - name: NFSServerType
        value: "kernel"
      - name: BackendStorageClass
        value: "cstor-csi"
      - name: FilePermissions
        data:
      #    UID: "1000"
      #    GID: "2000"
          mode: "0777"
provisioner: openebs.io/nfsrwx
reclaimPolicy: Delete