apiVersion: networking.k8s.io/v1
kind: "Ingress"
metadata:
  name: drupal-ingress
spec:
  defaultBackend:
    service:
      name: drupal-service
      port:
        number: 80
  tls:
  - secretName: "banilat-store-certificate"
  rules:
  - http:
      paths:
      - path: "/"
        backend:
          service:
            name: "drupal-service"
            port:
              number: 80
        pathType: "ImplementationSpecific"
    host: "banilat.store"
  - http:
      paths:
      - path: "/"
        backend:
          service:
            name: "drupal-service"
            port:
              number: 80
        pathType: "ImplementationSpecific"
    host: "www.banilat.store"
status:
  loadBalancer: {}
