apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
  labels:
    app: mysql
    app.kubernetes.io/name: mysql
data:
  MYSQL_ROOT_PASSWORD: admin
  MYSQL_DATABASE: drupal
  MYSQL_PASSWORD: admin
  TZ: America/Bogota

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: glusterfs-mysql-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  glusterfs:
    endpoints: glusterfs-cluster
    path: mysql
    readOnly: false
  storageClassName: glusterfs
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  ROOT_PASSWORD: YWRtaW4=
  DATABASE: ZHJ1cGFsCg==
  PASSWORD: YWRtaW4=
---
apiVersion: mysql.presslabs.org/v1alpha1
kind: MysqlCluster
metadata:
  name: drupal-mysql-cluster
  labels:
    app: mysql-cluster
spec:
  replicas: 3  
  secretName: mysql-secret
  volumeSpec:
    persistentVolumeClaim:
      accessModes: ["ReadWriteOnce"]
      storageClassName: glusterfs 
      resources:
        requests:
          storage: 5Gi