apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
  labels:
    app: mysql
    app.kubernetes.io/name: mysql
data:
  MYSQL_ROOT_PASSWORD: admin
  MYSQL_DATABASE: drupal
  MYSQL_PASSWORD: admin
  TZ: America/Bogota
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
    app.kubernetes.io/name: mysql
spec:
  ports:
  - name: mysql
    port: 3306
  type: ClusterIP
  selector:
    app: mysql
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  ROOT_PASSWORD: YWRtaW4=
  DATABASE: ZHJ1cGFsCg==
  PASSWORD: YWRtaW4=
---
apiVersion: mysql.presslabs.org/v1alpha1
kind: MysqlCluster
metadata:
  name: drupal-mysql-cluster
spec:
  replicas: 3  
  secretName: my-cluster-secret