apiVersion: v1
kind: Secret
metadata:
  name: drupal-secret
type: Opaque
data:
  database-user: cm9vdA==  # Base64 encoded 'root'
  database-password: YWRtaW4=  # Base64 encoded 'admin'
  user-password: QmFuaVNvbGEwMjYzKgo=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drupal-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drupal
  template:
    metadata:
      labels:
        app: drupal
    spec:
      securityContext: 
        fsGroup: 1001
      initContainers:
      - name: volume-permissions
        image: alpine
        command: ["sh", "-c", "mkdir -p /bitnami/drupal && chmod -R 777 /bitnami/drupal"]
        securityContext:
          runAsUser: 0
        volumeMounts:
        - name: drupal-storage
          mountPath: /bitnami/drupal
      containers:
      - name: drupal
        image: bitnami/drupal:10.1.5-debian-11-r3
        securityContext:
          runAsUser: 1001 
        ports:
        - containerPort: 8080
        env:
        - name: DRUPAL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: drupal-secret
              key: user-password
        - name: DRUPAL_USERNAME
          value: banisola
        - name: DRUPAL_EMAIL
          value: hfbanilatq@gmail.com
        - name: DRUPAL_DATABASE_HOST
          value: mysqlcluster.default.svc.cluster.local
        - name: DRUPAL_DATABASE_PORT_NUMBER
          value: "3306"
        - name: DRUPAL_DATABASE_NAME
          value: drupal
        - name: DRUPAL_DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: drupal-secret
              key: database-user
        - name: DRUPAL_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: drupal-secret
              key: database-password
        resources:
          requests:
            cpu: "400m"
            memory: "512Mi"
          limits:
            cpu: "800m"  
            memory: "1Gi"
        livenessProbe:
          httpGet:
            path: /user/login
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        volumeMounts:
        - name: drupal-storage
          mountPath: /bitnami/drupal
      volumes:
      - name: drupal-storage
        persistentVolumeClaim:
          claimName: drupalpvc
---
apiVersion: v1
kind: Service
metadata:
  name: drupal-service
spec:
  selector:
    app: drupal
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  sessionAffinity: None
  type: LoadBalancer
